# This Dockerfile is used to build a development environment for a Ruby on Rails application.
# It starts with the official Ruby 3.3.0-alpine image as the base image.

FROM ruby:3.3.0-alpine

# Install necessary dependencies for building the Rails application.
RUN apk add --no-cache git build-base libxml2-dev libxslt-dev mariadb-dev mariadb-client tzdata bash vim && \
  cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Set the environment variables for the application.
ENV APP_ROOT /app
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

ENV LANG=ja_JP.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3 \
  EDITOR=vim

# Update RubyGems and install Bundler.
RUN gem update --system && \
  gem install --no-document bundler:2.5.7

# Configure Bundler to force the correct Ruby platform.
RUN bundle config set force_ruby_platform true
